const Files = {
  brokerLandingPage: {
    googlePay:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/footer/googlePay.png",
    mentorImage:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Meet+our+founder/mentor.svg",
    angle:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Most+Compared+Brokers/angel.svg",
    upstox:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Most+Compared+Brokers/upstox.png",
    Zeerodha:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Most+Compared+Brokers/zeerodha.png",
    angleLogo:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Recommendation/angel-logo.svg",
    zerodhaLogo:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Recommendation/zerodha.svg",
    upstoxLogo:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/brokerage+landingpage/Recommendation/upstox.svg",
    heroBannerBG:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/backgroundIMG/HeroBanner.webp",
    stockBigginers:
      '"https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/Quiz/6.png"',
  },
  courses: {
    certificate1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/fundamental-analysis/certificate1.webp",
    certificate2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/certificate2.webp",
    comm1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm1.webp",
    comm2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm2.webp",
    comm3:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm3.webp",
    comm4:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm4.webp",
    comm5:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm5.webp",
    comm6:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm6.webp",
    comm7:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/comm7.webp",
    courseImageGirl:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/courseimg.webp",
    optionUser:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/optionuser.webp",
    prasad:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/prasad.webp",
    userss:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/userss.webp",
    youtube:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/youtube.svg",
    optionuser:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/fundamental-analysis-and-indian-stock-market-course-for-beginners/optionuser.webp",
    starSvg:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/fundamental-analysis-and-indian-stock-market-course-for-beginners/4.8.svg",
  },
  finClub: {
    financeBannerMobile:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/Finclub/Banner/finance_banner_mobile.svg",
    financeBanner:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/Finclub/Banner/finance_banner.svg",
    ct1Min:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/Finclub/CtaTop/cta1-min.png",
    joinclib:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/Finclub/Join+Club/joinClub.svg",
  },
  webinar: {
    askMeAnything:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/askmeanything.webp",
    bannerProfile:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/bannerProfile.svg",
    etThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/et_thumb.webp",
    frameIcon:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/frameicon.png",
    getMultiBaggerReturns:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/getmultibagger_returns.webp",
    mutualFund:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/getsahimutualfund.webp",
    girl: "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/girl.png",
    image1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image1.jpg",
    image2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image2.jpg",
    image3:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image3.jpg",
    image4:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image4.jpg",
    image6:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image6.jpg",
    jtThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/jt_thumb.webp",
    mintThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/mint_thumb.webp",
    paromitaBanerjee:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/ParomitaBanerjee.png",
    prasad:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/prasad.webp",
    rectAngle1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/Rectangle1518.png",
    rectAngle2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/Rectangle2.png",
    rectAngle3:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/Rectangle3.png",
    rightTime:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/righttime.webp",
    ttThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/tt_thumb.webp",
  },
  singleBlog: {
    blogSideBrImage1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/singleBlog/blogSidebarImg1.svg",
    blogSideBrImage2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/singleBlog/blogSidebarImg2.svg",
    indian:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/coures/courses/updated-2.webp",
  },
  singleBroker: {
    creator:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/singleBroker/creator.webp",
  },
  finnovationzLogo: {
    logo: "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/logo2.webp",
  },
  webinarCulture: {
    image1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/292A3177.JPG",
    image2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/5H9A9288.JPG",
    image3:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/AJP07414.JPG",
    // image4:
    //   "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/FIN09995.JPG",
    image5:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_0666.JPG",
    image6:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_0710.JPG",
    image7:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_0724.JPG",
    image8:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_0735.JPG",
    image9:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_0785.HEIC",
    image10:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_1489.HEIC",
    image11:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_1694.HEIC",
    image12:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_4637.JPG",
    image13:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_4655.JPG",
    image14:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/IMG_6609.JPG",
    image15:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/JSP08926.JPG",
    image16:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/Snapinsta.app_345886550_1952147545134206_1690436991466514973_n_1080+(1).jpg",
    image17:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/TEDx.jpg",
    image18:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/webinar/Webinar+Slideshow/VID_568150606_043853_313.mp4",
  },
  webinarCopy: {
    askMeAnything:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/askmeanything.webp",
    bannerProfile:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/bannerProfile.svg",
    etThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/et_thumb.webp",
    frameIcon:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/frameicon.png",
    getMultiBaggerReturns:
      "/1.png",
    mutualFund:
      "/2.png",
    girl: "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/girl.png",
    image1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image1.jpg",
    image2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image2.jpg",
    image3:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image3.jpg",
    image4:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image4.jpg",
    image6:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/image6.jpg",
    jtThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/jt_thumb.webp",
    mintThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/mint_thumb.webp",
    paromitaBanerjee:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/ParomitaBanerjee.png",
    prasad:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/prasad.webp",
    rectAngle1:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/Rectangle1518.png",
    rectAngle2:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/Rectangle2.png",
    rectAngle3:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/Rectangle3.png",
    rightTime:
      "/3.png",
    ttThumb:
      "https://websitevideos2020.s3.ap-south-1.amazonaws.com/finnovationz/money-mastery-programme/tt_thumb.webp",
  },
};

export default Files;
